version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    depends_on:
      - backend

  backend:
    build:
      context: ./server/time-tracker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server/time-tracker:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=time_tracker.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/timetracker
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=timetracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
