# Generated by Django 5.1.5 on 2025-04-10 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='staff',
            field=models.ManyToManyField(related_name='shift_staff', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan_company', to='management.company'),
        ),
        migrations.AddField(
            model_name='overage',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overage_subscription', to='management.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_plan_tier', to='management.subscriptiontier'),
        ),
        migrations.AddField(
            model_name='task',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_contract', to='management.contracts'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='selected_by',
            field=models.ManyToManyField(blank=True, related_name='task_selected_by', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='shift',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_shift', to='management.task'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.shift'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('name',)},
        ),
        migrations.AddIndex(
            model_name='employeecounthistory',
            index=models.Index(fields=['company', 'date'], name='management__company_cb04c3_idx'),
        ),
    ]
