# Generated by Django 5.1.5 on 2025-03-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_billingaddress_subscription_subscriptioninvoice'),
        ('staff', '0004_leave_end_time_leave_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='selected_by',
            field=models.ManyToManyField(related_name='task_selected_by', to='staff.staff'),
        ),
    ]
