# Generated by Django 5.1.5 on 2025-04-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_user_company_email_user_unique_owner_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_owner_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_email',
        ),
    ]
