# Generated by Django 5.1.5 on 2025-03-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_task_selected_by'),
        ('staff', '0005_timesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='selected_by',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='task_selected_by', to='staff.staff'),
        ),
    ]
