# Generated by Django 5.1.5 on 2025-03-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_shift_end_time_alter_shift_start_time_and_more'),
        ('staff', '0006_availability_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='selected_by',
            field=models.ManyToManyField(blank=True, related_name='task_selected_by', to='staff.staff'),
        ),
    ]
