# Generated by Django 5.1.5 on 2025-04-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_user_unique_owner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='required_number_of_staff',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='total_number_of_staff',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
