# Generated by Django 5.1.5 on 2025-03-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_shift_status_alter_task_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
