# Generated by Django 5.1.5 on 2025-04-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_taskcomment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhistory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
