# Generated by Django 5.1.5 on 2025-03-21 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_shift_end_date_shift_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptioninvoice',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='shift',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.shift'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_date', models.DateField()),
                ('base_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overage_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_company', to='management.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_count_history_company', to='management.company')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveIntegerField(choices=[(20, '20 employees'), (50, '50 employees'), (100, '100 employees'), (200, '200 employees'), (500, '500 employees'), (1000, '1000 employees'), (0, 'unlimited employees')])),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overage_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('renewal_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan_company', to='management.company')),
            ],
        ),
        migrations.CreateModel(
            name='Overage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('extra_employees', models.PositiveIntegerField()),
                ('overage_days', models.PositiveIntegerField()),
                ('calculated_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overage_subscription', to='management.subscriptionplan')),
            ],
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionInvoice',
        ),
        migrations.AddIndex(
            model_name='employeecounthistory',
            index=models.Index(fields=['company', 'date'], name='management__company_cb04c3_idx'),
        ),
    ]
