# Generated by Django 5.1.5 on 2025-04-26 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_subscriptionhistory_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan_company', to='management.company'),
        ),
    ]
