# Generated by Django 5.1.5 on 2025-03-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_subscriptiontier_remove_subscriptionplan_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontier',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
