# Generated by Django 5.1.5 on 2025-03-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_subscriptiontier_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
