# Generated by Django 5.1.5 on 2025-01-26 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_availability', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
