# Generated by Django 5.1.5 on 2025-02-04 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_billingaddress_subscription_subscriptioninvoice'),
        ('staff', '0002_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='trial_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='management.company'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
