# Generated by Django 5.1.5 on 2025-03-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_trial_end_date_alter_staff_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
