# Generated by Django 5.1.5 on 2025-03-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
