# Generated by Django 5.1.5 on 2025-03-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_availability_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
    ]
