# Generated by Django 5.1.5 on 2025-03-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_availability_availability_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='trial_end_date',
        ),
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
